apiVersion: v1
kind: Service
metadata:
  name: {{ include "echo-server.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "echo-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "echo-server.selectorLabels" . | nindent 4 }}
