apiVersion: v1
kind: Service
metadata:
  name: {{ include "workload.name" . }}
  namespace: {{ include "workload.namespace" . }}
  labels:
    {{- include "workload.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "workload.selectorLabels" . | nindent 4 }}
