{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "go-api.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    {{- include "go-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "go-api.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.prometheus.path }}
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
