apiVersion: v2
name: echo-server
description: A Helm chart for deploying the Echo Server in k3d
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - echo
  - redis
  - k3d
maintainers:
  - name: Sagar
    email: sagar@example.com
