#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Stub harness for shell tests (bats).
#
# SnowOps Labs's shell scripts do their work by calling kubectl, helm, k3d and
# friends. To test them hermetically we replace those binaries with recording
# shims placed first on PATH. A test then asserts on *what the script tried to
# do* rather than needing a cluster.
#
# Usage in a .bats file:
#
#   load '../helpers/stub'
#
#   setup() {
#     stub_setup
#     stub_command kubectl helm
#   }
#   teardown() { stub_teardown; }
#
#   @test "installs the chart idempotently" {
#     run bash platform/ingress/nginx/install.sh
#     [ "$status" -eq 0 ]
#     assert_called helm "upgrade --install"
#   }
#
# Portability: POSIX-ish bash only. No GNU-only flags (golden rule 1).

# stub_setup creates an isolated bin dir and call log, and puts the bin dir
# first on PATH. Call it from setup().
stub_setup() {
  STUB_DIR="$(mktemp -d "${TMPDIR:-/tmp}/snowops-stub.XXXXXX")"
  STUB_BIN="$STUB_DIR/bin"
  STUB_LOG="$STUB_DIR/calls.log"
  mkdir -p "$STUB_BIN"
  : >"$STUB_LOG"
  PATH="$STUB_BIN:$PATH"
  export PATH STUB_DIR STUB_BIN STUB_LOG
}

# stub_teardown removes the temp dir. Call it from teardown().
stub_teardown() {
  if [ -n "${STUB_DIR:-}" ] && [ -d "$STUB_DIR" ]; then
    rm -rf "$STUB_DIR"
  fi
}

# stub_command <name>... creates recording shims that succeed silently.
stub_command() {
  local name
  for name in "$@"; do
    mkdir -p "$STUB_DIR/spec/$name"
    : >"$STUB_DIR/spec/$name/exit"
    echo 0 >"$STUB_DIR/spec/$name/exit"
    : >"$STUB_DIR/spec/$name/stdout"
    : >"$STUB_DIR/spec/$name/rules"
    cat >"$STUB_BIN/$name" <<STUB
#!/usr/bin/env bash
# Recording stub for '$name' generated by test/shell/helpers/stub.bash.
printf '%s\t%s\n' "$name" "\$*" >>"$STUB_LOG"

spec="$STUB_DIR/spec/$name"

# Per-invocation rules win over the default, first match by argument substring.
# Rule format: <match><TAB><exit><TAB><stdout>
if [ -s "\$spec/rules" ]; then
  while IFS="\$(printf '\t')" read -r match code out; do
    [ -n "\$match" ] || continue
    case "\$*" in
      *"\$match"*)
        [ -n "\$out" ] && printf '%s\n' "\$out"
        exit "\${code:-0}"
        ;;
    esac
  done <"\$spec/rules"
fi

[ -s "\$spec/stdout" ] && cat "\$spec/stdout"
exit "\$(cat "\$spec/exit")"
STUB
    chmod +x "$STUB_BIN/$name"
  done
}

# stub_exit <name> <code> — make every call to <name> exit with <code>.
# Use this to prove a script propagates tool failure (set -euo pipefail).
stub_exit() {
  echo "$2" >"$STUB_DIR/spec/$1/exit"
}

# stub_stdout <name> <text> — make <name> print <text> on every call.
stub_stdout() {
  printf '%s\n' "$2" >"$STUB_DIR/spec/$1/stdout"
}

# stub_when <name> <arg-substring> <exit-code> [stdout]
# Behave differently when the arguments contain <arg-substring>. Rules are
# evaluated in the order added and the first match wins, so add the most
# specific rule first. Example: helm 'list' returns a release, 'upgrade' fails.
stub_when() {
  printf '%s\t%s\t%s\n' "$2" "$3" "${4:-}" >>"$STUB_DIR/spec/$1/rules"
}

# calls_for <name> — print the argument line of every call to <name>.
calls_for() {
  # shellcheck disable=SC2001  # portable substitution, no bash-only expansion
  grep "^$1$(printf '\t')" "$STUB_LOG" | sed "s/^[^$(printf '\t')]*$(printf '\t')//"
}

# call_count <name> [arg-substring] — number of matching calls.
call_count() {
  if [ -n "${2:-}" ]; then
    calls_for "$1" | grep -c -- "$2" || true
  else
    calls_for "$1" | grep -c '' || true
  fi
}

# assert_called <name> [arg-substring] — fail unless <name> was called (with
# arguments containing <arg-substring>, when given).
assert_called() {
  local n
  n="$(call_count "$1" "${2:-}")"
  if [ "$n" -eq 0 ]; then
    printf 'expected %s to be called' "$1" >&2
    [ -n "${2:-}" ] && printf ' with arguments containing %s' "$2" >&2
    printf '\nrecorded calls:\n%s\n' "$(cat "$STUB_LOG")" >&2
    return 1
  fi
}

# refute_called <name> [arg-substring] — fail if <name> was called.
# The idempotency assertion: a second run must make no destructive call.
refute_called() {
  local n
  n="$(call_count "$1" "${2:-}")"
  if [ "$n" -ne 0 ]; then
    printf 'expected %s NOT to be called' "$1" >&2
    [ -n "${2:-}" ] && printf ' with arguments containing %s' "$2" >&2
    printf '\nrecorded calls:\n%s\n' "$(cat "$STUB_LOG")" >&2
    return 1
  fi
}

# assert_call_count <name> <expected> [arg-substring]
assert_call_count() {
  local n
  n="$(call_count "$1" "${3:-}")"
  if [ "$n" -ne "$2" ]; then
    printf 'expected %s calls to %s, got %s\nrecorded calls:\n%s\n' \
      "$2" "$1" "$n" "$(cat "$STUB_LOG")" >&2
    return 1
  fi
}

# reset_calls clears the call log without recreating the stubs. Use it between
# the first and second run of an idempotency test.
reset_calls() {
  : >"$STUB_LOG"
}

# project_root prints the repository (content) root, so tests can invoke
# scripts by a path that does not depend on where bats was started. The bats
# suites moved under src/test/shell with the rest of the Go engine, so this
# walks up one extra level: helpers -> shell -> test -> src -> repo root.
project_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd
}
