{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) .Values.auth.users }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "labctl-server.usersSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labctl-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  users.yaml: |
    users:
    {{- range .Values.auth.users }}
      - name: {{ .name | quote }}
        role: {{ .role | quote }}
        passwordHash: {{ .passwordHash | quote }}
    {{- end }}
{{- end }}
